services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: investor-feed-frontend
    ports:
      - "8081:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - investor-feed-network

networks:
  investor-feed-network:
    driver: bridge
